# Generated by Django 4.1.7 on 2023-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_at',)},
        ),
    ]
